# Generated by Django 6.0.5 on 2026-06-01 10:13

from django.db import migrations, models


def set_null_descriptions_to_empty(apps, schema_editor):
    Title = apps.get_model('reviews', 'Title')
    Title.objects.filter(description__isnull=True).update(description='')


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            set_null_descriptions_to_empty,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
